In [1]:
#import pandas
import pandas as pd

In [4]:
#create pandas series using list
data=[10,20,30,40]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [5]:
data=[10,20,30,40,'A']
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4     A
dtype: object


In [7]:
#create a pandas serice using a custom index
data=[1,2,3,4]
i=['A','B','C','D']
series=pd.Series(data,index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [8]:
#create a pandas series using dictionary
data={'A':10,'B':20,'C':30}
series=pd.Series(data)
print(series)

A    10
B    20
C    30
dtype: int64


In [9]:
#create a pandas series using numpy array
#import numpy
import numpy as np

In [10]:
data=np.array([100,200,300])
series=pd.Series(data,index=['a','b','c'])
print(series)

a    100
b    200
c    300
dtype: int32


In [11]:
#create pandas dataframe from dictionary of lists
data={'Name':['Alice','Bob','Mary'],'Age':[25,30,34],'Country':['USA','UK','AUS']}
df=pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2   Mary   34     AUS


In [14]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df=pd.DataFrame(array,columns=['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [15]:
data=[[1,'Alice',25],[2,'Bob',30],[3,'Mary',34]]
print(data)
df=pd.DataFrame(array,columns=['ID','Name','Age'])
print(df)

[[1, 'Alice', 25], [2, 'Bob', 30], [3, 'Mary', 34]]
   ID  Name  Age
0   1     2    3
1   4     5    6
2   7     8    9


In [18]:
iris_df=pd.read_csv("iris.csv")
print(iris_df)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]


In [20]:
iris_df=pd.read_csv("iris.xls")
print(iris_df)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte